### ISSUE TITLE
Update forge

### ISSUE THREAD

**Issue by bigenergy** [CatServer/CatServer#27]
Hello, @CatServer ! Please update forge to last version.
Thanks!

**Comment by CatServer** [comment]
Hello, Forge has been updated to 2825, CatServer's Forge version update will choose a stable version
In the latest version, you can change the Build version of Forge by modifying the settings, but the actual code has not changed. If you just need a high version number and won't use the updated code, you can try it.
Example: Create a file catserver.yml in the root directory and write to 
```
ForgeBuildVersion: 2768
```
