### ISSUE TITLE
加载LagGoggles和FastWorkbench会崩溃，以及在后台无法使用tab补全指令

### ISSUE THREAD

**Issue by Leaveleaf** [CatServer/CatServer#30]
LagGoggles-FORGE-1.12.2-4.3-HOTFIX在coremod阶段就加载不了
https://paste.ubuntu.com/p/zwTJRcWnWj/
https://paste.ubuntu.com/p/JmSVpCBVcz/
FastWorkbench-1.12.2-1.7.1在中后期阶段崩溃
https://paste.ubuntu.com/p/PySBHbGPxF/

还有更重要的问题，那就是在后台无法使用tab补全指令，这很过分

**Comment by IceSoulHanxi** [comment]
FastWorkbench解决方法:
找到config/fastbench.cfg 将内容
`B:"Disable Recipe Book"=true` 改成
`B:"Disable Recipe Book"=false`

**Comment by IceSoulHanxi** [comment]
Tab补全的话 我自己测试是没问题的
![tab补全](https://user-images.githubusercontent.com/17005758/57977223-83cb5e80-7a26-11e9-880f-b0f9cf6dc775.png)

**Comment by Leaveleaf** [comment]
这就很奇怪了，但是后续我放弃使用它了，cat比客户端多注册了四个物品
![image](https://user-images.githubusercontent.com/19620848/57977267-4915f600-7a27-11e9-8f9c-ff02d90e20ab.png)

**Comment by IceSoulHanxi** [comment]
试试这个吧: https://minecraft.curseforge.com/projects/jeid

**Comment by Leaveleaf** [comment]
好的，我试试

**Comment by Leaveleaf** [comment]
![image](https://user-images.githubusercontent.com/19620848/57977469-e83cec80-7a2b-11e9-8d20-fa9125fc7b77.png)
并不行，还是会比客户端多注册四个方块，客户端丢失群戏那个问题不大，在forge端就丢失了
https://paste.ubuntu.com/p/4NgjRwyHjk/

**Comment by IceSoulHanxi** [comment]
emmmm 你加了QQ群吗

**Comment by Leaveleaf** [comment]
猫端群没加，但是在像素谷
