### ISSUE TITLE
Pixelmon Permissions don't work!!

### ISSUE THREAD

**Issue by MaxIsH0t** [CatServer/CatServer#32]
group.default:
       description: This is for the default group.
       default: true
       children:
          pdrewards.base.claim: true
          pdrewards.base.remaining: true
          pdrewards.base.count: true
          com.pixelmonmod.pixelmon.commands.EndBattle: true
          pixelmon.command.endbattle: true

I have this as my permission.yml file and have the permissions added to my user with permissionex plugin. I do /endbattle and it says "no permission" but the command works when I am opped.

**Comment by IceSoulHanxi** [comment]
Hmmmmm Mod permissions are redirected to minecraft.command.XXXX in CatServer
