### ISSUE TITLE
Error when start server. Instant-Massive-Structures-Mod 1.12.2

### ISSUE THREAD

**Issue by TheLimmo** [CatServer/CatServer#36]
Instant-Massive-Structures-Mod 1.12.2

https://pastebin.com/5T70JFCt

---- Отчет о сбое Minecraft ----

ВНИМАНИЕ: присутствуют 
coremods : SignPictureCorePlugin (SignPicture-Mod-1.12.2.jar) 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar) 
Свяжитесь с их авторами ДО контакта с forge

// Теперь мне грустно :(

Время: 23.05.19 19:02 
Описание: Исключение в тиковом цикле сервера

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net / minecraft / client / multiplayer / WorldClient по 
адресу net.minecraftforge.fml.common.AutomaticEventSubscriber.inject (AutomaticEventSubscriber.java:89) 
в сети net.mine .common.FMLModContainer.constructMod (FMLModContainer.java:599) 
в sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method) 
в sun.reflect.NativeMethodAccessorImpl.invoke (Unknown Source) 
в sun.reflect.DelegatingMethodAccessorImpl.invoke (Unknown Source) 
в java.lang.reflect.Method.invoke (Неизвестный источник) 
на com.google.common.eventbus.Subscriber.invokeSubscriberMethod (Subscriber.java:91)
на com.google.common.eventbus.Subscriber $ SynchronizedSubscriber.invokeSubscriberMethod (Subscriber.java:150) 
на com.google.common.eventbus.Subscriber $ 1.run (Subscriber.java:76) 
на com.google.common.util. concurrent.MoreExecutors $ DirectExecutor.execute (MoreExecutors.java:399) 
на com.google.common.eventbus.Subscriber.dispatchEvent (Subscriber.java:71) 
на com.google.common.eventbus.Dispatcher $ PerThreadQueuedDispatcher.dispatch. Java: 116) 
на com.google.common.eventbus.EventBus.post (EventBus.java:217) 
на net.minecraftforge.fml.common.LoadController.sendEventToModContainer (LoadController.java:218) 
на net.minecraftforge.fml.common .LoadController.propogateStateMessage (LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0 (собственный метод) 
в sun.reflect.NativeMethodAccessorImpl.invoke (неизвестный источник) 
в sun.reflect.DelegatingMethodAccessorImpl.invoke (неизвестный источник) 
в java.lanke.hof (неизвестный) 
на com.google.common.eventbus.Subscriber.invokeSubscriberMethod (Subscriber.java:91) 
на com.google.common.eventbus.Subscriber $ SynchronizedSubscriber.invokeSubscriberMethod (Subscriber.java:150) 
на com.google.coms $ 1.run (Subscriber.java:76) 
на com.google.common.util.concurrent.MoreExecutors $ DirectExecutor.execute (MoreExecutors.java:399) 
на com.google.common.eventbus.Subscriber.dispatchEvent (Subscriber.java: 71)
на com.google.common.eventbus.Dispatcher $ PerThreadQueuedDispatcher.dispatch (Dispatcher.java:116) 
на com.google.common.eventbus.EventBus.post (EventBus.java:217) 
на net.minecraftforge.fml.common.LoadController .distributeStateMessage (LoadController.java:135) 
на net.minecraftforge.fml.common.Loader.loadMods (Loader.java:593) 
на net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading (FMLServerHandler.java:98) 
. minecraftforge.fml.common.FMLCommonHandler.onServerStart (FMLCommonHandler.java:333) по 
адресу net.minecraft.server.dedicated.DedicatedServer.func_71197_b (DedicatedServer.java:125) по 
адресу net.minecraft.server.MinecraftServerSunver.un 486) 
на java.lang.Thread.run (неизвестный источник)
Вызывается: java.lang.NoClassDefFoundError: net / minecraft / client / multiplayer / WorldClient 
в java.lang.Class.getDeclaredMethods0 (собственный метод) 
в java.lang.Class.privateGetDeclaredMethods (неизвестный источник) 
в java.priettsCount (Неизвестный источник) 
в java.lang.Class.getMethods (Неизвестный источник) 
в net.minecraftforge.fml.common.eventhandler.EventBus.register (EventBus.java:82) 
в net.minecraftforge.fml.common.AutomaticEventSubscriber.inject ( AutomaticEventSubscriber.java:82) 
... еще 32 
Вызвано: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient 
в net.minecraft.launchwrapper.LaunchClassLoader.findClass (LaunchClassLoader.java:191)
на java.lang.ClassLoader.loadClass (неизвестный источник) 
на java.lang.ClassLoader.loadClass (неизвестный источник) 
... еще 38 
причин: net.minecraftforge.fml.common.asm.ASMTransformerWrapper $ TransformerException: исключение в преобразователе класса net.minecraftforge.fml.common.asm.transformers.SideTransformer@435ce306 от coremod FMLCorePlugin по 
адресу net.minecraftforge.fml.common.asm.ASMTransformerWrapper $ TransformerWrapper.transform (ASMTransformerWrapper.java:2LL) 
. runTransformers (LaunchClassLoader.java:279) 
в net.minecraft.launchwrapper.LaunchClassLoader.findClass (LaunchClassLoader.java:176) 
... ... еще 40 Причин 
: java.lang.RuntimeException: Попытка загрузить класс bsb для недопустимой стороны SERVER
в net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform (SideTransformer.java:62) 
в net.minecraftforge.fml.common.asm.ASMTransformerWrapper $ TransformerWrapper.transform (ASMTransformerWrapper.java:256) 
42 Больше

Подробное описание ошибки, пути к ее коду и всех известных подробностей приведено ниже:
- Сведения о системе - 
Детали: 
Minecraft Версия: 1.12.2 
Операционная система: Windows 10 (amd64) версия 10.0 
Версия Java: 1.8.0_191, Oracle Corporation 
Версия Java VM: 64-разрядная виртуальная машина Java HotSpot (TM) (смешанный режим) ), Oracle Corporation 
Память: 6663201880 байт (6354 МБ) / 6848774144 байт (6531 МБ) до 8589934592 байт (8192 МБ) 
Флаги JVM: всего 2; -Xms6G -Xmx9G 
IntCache: кэш: 0, tcache: 0, выделено: 0, выделено: 0 
FML: MCP 9.42 Работает на Forge 14.23.5.2768 Работает 23 мода, 23 активных режима 
Состояния: 'U' = не загружено 'L' = загружено 'C' = Построен 'H' = Предварительно инициализирован 'I' = Инициализирован 'J' = Постинициализирован 'A' = Доступен 'D' = Отключен 'E' = Ошибка

| State | ID                     | Version      | Source                                                      | Signature                                |
|:----- |:---------------------- |:------------ |:----------------------------------------------------------- |:---------------------------------------- |
| UC    | minecraft              | 1.12.2       | minecraft.jar                                               | None                                     |
| UC    | mcp                    | 9.42         | minecraft.jar                                               | None                                     |
| UC    | FML                    | 8.0.99.99    | forge-1.12.2-14.23.5.2768-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UC    | forge                  | 14.23.5.2768 | forge-1.12.2-14.23.5.2768-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UC    | obfuscate              | 0.2.6        | minecraft.jar                                               | None                                     |
| UC    | architecturecraft      | @VERSION@    | architecturecraft-1.12-2.68.jar                             | None                                     |
| UC    | mts                    | 12.2.1       | MinecraftTransportSimulator_1.12.2_12.2.1.jar               | None                                     |
| UC    | unuparts               | 1.6.1        | UNUPartsPackMTS1.10.2_12.2.0_1.6.1.jar                      | None                                     |
| UC    | blackthorne            | 1.6.1        | BlackThorneEmpireVehiclesMTSIR1.10.2_12.2.0_1.4.1_1.6.1.jar | None                                     |
| UC    | customnpcs             | 1.12         | CustomNPCs_1.12.230Jan19.jar                                | None                                     |
| UC    | ptrmodellib            | 1.0.0        | Decocraft-2.5.5_1.12.2.jar                                  | None                                     |
| UC    | props                  | 2.5.5        | Decocraft-2.5.5_1.12.2.jar                                  | None                                     |
| UE    | imsm                   | 1.12         | Instant-Massive-Structures-Mod-1.12 (1).jar                 | None                                     |
| U     | mtsseagullcivilpack    | 2.0.0        | MTS+Seagull's+civil+pack+1.11.0.jar                         | None                                     |
| U     | mtsseagulltrinpartpack | 1.0.0        | MTS+seagull's+trin+parts+pack+1.4.0.jar                     | None                                     |
| U     | mtsofficialpack        | 8.0.0        | MTS_Official_Pack_V08.jar                                   | None                                     |
| U     | rcroads                | 0.3.0        | RC+Roads+0.3.0.jar                                          | None                                     |
| U     | rebelcraft             | 0.1          | RebelCraftV022.jar                                          | None                                     |
| U     | signpic                | 2.8.1        | SignPicture-Mod-1.12.2.jar                                  | None                                     |
| U     | t3gssksignspack        | 1.0.1        | tim3gameseuropeansignspack1.0.1.jar                         | None                                     |
| U     | vehicle                | 0.33.0       | vehicle-mod-0.33.0-1.12.2.jar                               | None                                     |
| U     | imvoice                | 0.7.0        | voicechat-1.12.2-0.7.0.jar                                  | None                                     |
| U     | worldedit              | 6.1.8        | worldedit_forge_mc1.12_6.1.8_dist.jar                       | None                                     |

Loaded coremods (and transformers):

**Comment by IceSoulHanxi** [comment]
Can the mod run on a forge server?
