### ISSUE TITLE
关于遵守GNU相关协议的警告

### ISSUE THREAD

**Issue by CreeperKong** [CatServer/CatServer#47]
根据LGPL第4条的d部分规定，开发者需要提供最小的源码副本（适用于Forge）

根据GPL第6条的a和d部分规定，您必须将源代码同时发布（适用于Spigot），同时根据第8条相关规定可以终止授权

如果你们坚持不开源，我们GNU支持者将把你网站攻击的稀巴烂

**Comment by NKid00** [comment]
资瓷资瓷

**Comment by CreeperKong** [comment]
我已经通知spigot作者，作者将处理相关事宜，谢谢
