### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by AshBTA** [CatServer/CatServer#51]
Internal Exception: com.gogole.common.util.concurrent.UncheckedExecutionException: java.land.IllegalStateExce[topm: Recipe minecraft:wheat (net.minecraft.item.crafting.ShapedRecipes@2773504f) produces unregistered item minecraft:wheat (net.minecraft.item.item@596afb2f)

its not mods

**Comment by zandercodes** [comment]
Whats is the Java version?
