### ISSUE TITLE
Cant Start Catserver. Pls. Help!

### ISSUE THREAD

**Issue by PocketbikeUpload** [CatServer/CatServer#53]
i have a problem.
I want to start the Catserver Using MCMyAdmin3 on AMP
Basically its just a server.
I already Created all Catserver files, and then i Uploaded Everything to The Server File.
When i Start The Server via. CatServer-git-4b6a920-Community.jar
The Server Basically dont Starts.
When i Start the Server via. minecraft_server.1.12.2.jar
The Server starts in Basic Vanilla (No Plugins and Mods)
What do i Wrong?

**Comment by PocketbikeUpload** [comment]
I Noticed that i have to start the Run.bat ,
on my PC it works but i cant start a .bat file in AMP..
Sombody can help me? thx.

**Comment by lildevuwu** [comment]
No clue, if it's some hosting, maybe they don't allow custom jars?
