### ISSUE TITLE
比较难过的是：AOA3传送到异世界之后cat端的异世界没有回去的传送门，深渊也没传送到对应的位置

### ISSUE THREAD

**Issue by kerocate** [CatServer/CatServer#56]
如题：
比较难过的是：AOA3传送到异世界之后cat端的异世界没有回去的传送门，深渊也没传送到对应的位置

原本是在自己整合里面发现的，换了最新版的cat和aoa3单独测试也有这个问题

单forge的端没有问题

**Comment by leeorb** [comment]
可以使用带类似/home命令的插件

**Comment by Luohuayu** [comment]
78df914已修复

**Comment by kerocate** [comment]
> 78df914已修复

嗷，开心的从床上跳起来惹，那是新版本还没上传吗qwq，而且好像我发现只要是个异世界传送门就不正常嗷之前那个问题，我的描述还有点不大对劲的说

**Comment by Luohuayu** [comment]
> 
> 
> > 78df914已修复
> 
> 嗷，开心的从床上跳起来惹，那是新版本还没上传吗qwq，而且好像我发现只要是个异世界传送门就不正常嗷之前那个问题，我的描述还有点不大对劲的说

http://catsever.moe 在这下最新的

**Comment by kerocate** [comment]
> > > 78df914已修复
> > 
> > 
> > 嗷，开心的从床上跳起来惹，那是新版本还没上传吗qwq，而且好像我发现只要是个异世界传送门就不正常嗷之前那个问题，我的描述还有点不大对劲的说
> 
> http://catsever.moe 在这下最新的

 你们的服务器看起来有点不大好嗷，连不上去嗷

**Comment by Luohuayu** [comment]
> 
> 
> > > > 78df914已修复
> > > 
> > > 
> > > 嗷，开心的从床上跳起来惹，那是新版本还没上传吗qwq，而且好像我发现只要是个异世界传送门就不正常嗷之前那个问题，我的描述还有点不大对劲的说
> > 
> > 
> > http://catsever.moe 在这下最新的
> 
> 你们的服务器看起来有点不大好嗷，连不上去嗷。还是说我不大会用（跑

打错 catserver.moe
