### ISSUE TITLE
PlaceBlock Problem 

### ISSUE THREAD

**Issue by fantahund** [CatServer/CatServer#58]
I have the following problem.
I use CoreProtect for logging interactions. When a block is set. 
Says CoreProtect that the block was set and dismantled immediately.

http://prntscr.com/owrc0x

**Comment by fantahund** [comment]
The block was not dismantled

**Comment by fantahund** [comment]
LogBlock has the same problem :(

**Comment by Luohuayu** [comment]
All of plugin can't get mod block, Forge's some block is the same as the item id. This is different from vanilla so the plugin can't handle it.

**Comment by fantahund** [comment]
The problem is that I have 2 entries in the database. When I put a block.
Block place and block break, only when I place a block

**Comment by fantahund** [comment]
???

**Comment by fantahund** [comment]
can you fix the Problem???

**Comment by fantahund** [comment]
No more interest. I have changed server software
