### ISSUE TITLE
mcmmo无法识别mod方块

### ISSUE THREAD

**Issue by StarchierOrb** [CatServer/CatServer#7]
玩家与mod方块互动时，后台会报错nullpointerexception，（好像其他插件例如mangoquest也无法识别mod方块）
报错：
log： https://paste.ubuntu.com/p/Yjf2P5JzQc/

**Comment by StarchierOrb** [comment]
log url： https://paste.ubuntu.com/p/Yjf2P5JzQc/

**Comment by KomiMoe** [comment]
无解
